### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by herohamp** [Newawe/newawe#87]
```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Object.<anonymous> (/home/pi/Desktop/newawe-node/server.js:47:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

**Comment by Mrcomputer1** [comment]
There is a missing `}` in config.json which I fixed

**Comment by herohamp** [comment]
Ok I will update it when I get home

**Comment by Mrcomputer1** [comment]
Ok
